name: Pharma Api Deploy
run-name: Deploy new version of Pharma NestJs API
on:
  push:
    branches:
      - ci/hml
      - feat/add-github-actions-pipeline
permissions:
  id-token: write
  contents: read
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: HML
    env:
      TAG: ${{ github.sha }}
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v5
      - name: Build Docker image and set Docker TAG
        run: |
          echo "Generated Docker tag: $TAG"
          docker build -t "${{ secrets.REPOSITORY_NAME }}" .
          docker tag "${{ secrets.REPOSITORY_NAME }}" "${{ secrets.AWS_REGISTRY_URL }}/${{ secrets.REPOSITORY_NAME }}:latest"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::133802582104:role/GitHubAction
          aws-region: sa-east-1
      - name: Push docker image to AWS ECR
        run: |
          aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_REGISTRY_URL }}
          docker push "${{ secrets.AWS_REGISTRY_URL }}/${{ secrets.REPOSITORY_NAME }}:latest"
